server:
  port: 8082
  servlet:
    context-path: /

logging:
  level:
    root: info
    com.gxh.controller: debug
    com.gxh.dao: debug

spring:
  main:
    banner-mode: off
  banner:
    location: static/banner/banner.txt
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/situ_prj_02_boot
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
    enabled: true
#    prefix: classpath:/templates/
#    suffix: html
    encoding: utf-8
  servlet:
#    文件上传大小限制
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.web.servlet.MultipartAutoConfiguration
#    mode: LEGACYHTML5
#    servlet:
#      content-type: text/html

mybatis-plus:
  configuration:
    #日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/gxh/mapper/*Mapper.xml
  global-config:
    banner: off
    db-config:
      #逻辑删除字段名
      logic-delete-field: deleted
      #逻辑删除字段值：删除为1
      logic-delete-value: 1
      #逻辑删除字段值：未删除为0
      logic-not-delete-value: 0
upload:
#  path: D:\PORJECT\Prj_IDEA\SiTuPrj_02_Boot\src\main\resources\static\img\upload\
  path: D:\PORJECT\Prj_IDEA\situ_Prj_Parent\frontPage\src\main\resources\static\img\upload\

#PageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
